CREATE TABLE [ProdcopyStg].[Contact_old]
(
[accountid] [uniqueidentifier] NULL,
[accountidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountrolecode] [int] NULL,
[accountrolecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_addressid] [uniqueidentifier] NULL,
[address1_addresstypecode] [int] NULL,
[address1_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_freighttermscode] [int] NULL,
[address1_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_latitude] [float] NULL,
[address1_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_longitude] [float] NULL,
[address1_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_shippingmethodcode] [int] NULL,
[address1_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_utcoffset] [int] NULL,
[address2_addressid] [uniqueidentifier] NULL,
[address2_addresstypecode] [int] NULL,
[address2_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_freighttermscode] [int] NULL,
[address2_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_latitude] [float] NULL,
[address2_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_longitude] [float] NULL,
[address2_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_shippingmethodcode] [int] NULL,
[address2_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_utcoffset] [int] NULL,
[address3_addressid] [uniqueidentifier] NULL,
[address3_addresstypecode] [int] NULL,
[address3_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_freighttermscode] [int] NULL,
[address3_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_latitude] [float] NULL,
[address3_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_longitude] [float] NULL,
[address3_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_shippingmethodcode] [int] NULL,
[address3_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_utcoffset] [int] NULL,
[aging30] [money] NULL,
[aging30_base] [money] NULL,
[aging60] [money] NULL,
[aging60_base] [money] NULL,
[aging90] [money] NULL,
[aging90_base] [money] NULL,
[anniversary] [datetime] NULL,
[annualincome] [money] NULL,
[annualincome_base] [money] NULL,
[assistantname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assistantphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthdate] [datetime] NULL,
[business2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[callback] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_age] [int] NULL,
[cdi_allowtextmessages] [bit] NULL,
[cdi_allowtextmessagesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_facebook] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_gender] [bit] NULL,
[cdi_gendername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_grade] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_identifiedon] [datetime] NULL,
[cdi_image] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_ip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_latitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_longitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_partitionkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_rowkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_score] [int] NULL,
[cdi_social] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_totalscore] [int] NULL,
[cdi_twitter] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_visitorkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[childrensnames] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_bwcontactid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_contactme] [int] NULL,
[client_contactmename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_falcons2016schedule] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_falconshomeopponents] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_falconssth] [bit] NULL,
[client_falconssthname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_gadomepremiumevents] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_gadomeseatingpreferences] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_gpaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_gpcustomerclass] [int] NULL,
[client_gpcustomerclassname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kiabuyer] [bit] NULL,
[client_kiabuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_preferredlanguage] [int] NULL,
[client_preferredlanguagename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_primaryrep] [uniqueidentifier] NULL,
[client_primaryrepemail] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_primaryrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_primaryrepphone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_primaryrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_repricecalls] [int] NULL,
[client_repricecallsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_sp_allowsms] [bit] NULL,
[client_sp_allowsmsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_sp_lastclick] [datetime] NULL,
[client_sp_lastopen] [datetime] NULL,
[client_sp_lastsend] [datetime] NULL,
[client_triggergp] [bit] NULL,
[client_triggergpname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_upgradecalls] [int] NULL,
[client_upgradecallsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdeventsignup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdhomeopponents] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdseasonschedule] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdseatingpreferences] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contactid] [uniqueidentifier] NOT NULL,
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creditlimit] [money] NULL,
[creditlimit_base] [money] NULL,
[creditonhold] [bit] NULL,
[creditonholdname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customersizecode] [int] NULL,
[customersizecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customertypecode] [int] NULL,
[customertypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defaultpricelevelid] [uniqueidentifier] NULL,
[defaultpricelevelidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[department] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkemail] [bit] NULL,
[donotbulkemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkpostalmail] [bit] NULL,
[donotbulkpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotemail] [bit] NULL,
[donotemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotfax] [bit] NULL,
[donotfaxname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotphone] [bit] NULL,
[donotphonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotpostalmail] [bit] NULL,
[donotpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmarketingmaterialname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmm] [bit] NULL,
[educationcode] [int] NULL,
[educationcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employeeid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimage] [varbinary] (max) NULL,
[entityimage_timestamp] [bigint] NULL,
[entityimage_url] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimageid] [uniqueidentifier] NULL,
[exchangerate] [decimal] (28, 0) NULL,
[externaluseridentifier] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[familystatuscode] [int] NULL,
[familystatuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstname] [nvarchar] (74) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftpsiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fullname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gendercode] [int] NULL,
[gendercodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[governmentid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[haschildrencode] [int] NULL,
[haschildrencodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[importsequencenumber] [int] NULL,
[isbackofficecustomer] [bit] NULL,
[isbackofficecustomername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isprivatename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[jobtitle] [nvarchar] (112) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountaliasid] [uniqueidentifier] NULL,
[kore_accountaliasidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountnumbers] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1_telephone1dncstatus] [bit] NULL,
[kore_address1_telephone1dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1_telephone2dncstatus] [bit] NULL,
[kore_address1_telephone2dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1_telephone3dncstatus] [bit] NULL,
[kore_address1_telephone3dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1milesfromfacility] [decimal] (28, 0) NULL,
[kore_address2_telephone1dncstatus] [bit] NULL,
[kore_address2_telephone1dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address2_telephone2dncstatus] [bit] NULL,
[kore_address2_telephone2dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address2_telephone3dncstatus] [bit] NULL,
[kore_address2_telephone3dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_archticsids] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_assistantphonedncstatus] [bit] NULL,
[kore_assistantphonedncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_attentionname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwbasedate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwcompanyid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwcontactid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwsequence] [int] NULL,
[kore_checkedoutbyid] [uniqueidentifier] NULL,
[kore_checkedoutbyidname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_checkedoutbyidyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_checkedoutuntil] [datetime] NULL,
[kore_companyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_countryid] [uniqueidentifier] NULL,
[kore_countryidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_externalcontactid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupbuyer] [bit] NULL,
[kore_groupbuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupcategory] [int] NULL,
[kore_groupcategoryname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupsalesrep] [uniqueidentifier] NULL,
[kore_groupsalesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupsalesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_heritagenationality] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_importid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_invoicebalance] [money] NULL,
[kore_invoicebalance_base] [money] NULL,
[kore_isbillingcontact] [bit] NULL,
[kore_isbillingcontactname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_isprimarycontact] [bit] NULL,
[kore_isprimarycontactname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastcontacted] [datetime] NULL,
[kore_lastcontactedbyid] [uniqueidentifier] NULL,
[kore_lastcontactedbyidname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastcontactedbyidyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastsync] [datetime] NULL,
[kore_listattributename] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_listattributevalue] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_managerphonedncstatus] [bit] NULL,
[kore_managerphonedncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_milesfromfacility] [decimal] (28, 0) NULL,
[kore_miniplanholder] [bit] NULL,
[kore_miniplanholdername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_mobilephonedncstatus] [bit] NULL,
[kore_mobilephonedncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_optoutofduplicatedetection] [bit] NULL,
[kore_optoutofduplicatedetectionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_overridecheckoutexpiration] [bit] NULL,
[kore_overridecheckoutexpirationname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_parentcustomeridstrippedname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryarchticsid] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_seasonticketholder] [bit] NULL,
[kore_seasonticketholdername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondaryarchticsname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondaryemail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_senioritydate] [datetime] NULL,
[kore_sincedate] [datetime] NULL,
[kore_sourcemarketinglistid] [uniqueidentifier] NULL,
[kore_sourcemarketinglistidname] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_sponsoraccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[kore_stateorprovinceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitebuyer] [bit] NULL,
[kore_suitebuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitesalesrep] [uniqueidentifier] NULL,
[kore_suitesalesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitesalesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone1dncstatus] [bit] NULL,
[kore_telephone1dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone1dncstatustype] [int] NULL,
[kore_telephone1dncstatustypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone2dncstatus] [bit] NULL,
[kore_telephone2dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone2dncstatustype] [int] NULL,
[kore_telephone2dncstatustypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone3dncstatus] [bit] NULL,
[kore_telephone3dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone3dncstatustype] [int] NULL,
[kore_telephone3dncstatustypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingcontacttype] [int] NULL,
[kore_ticketingcontacttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingsalesrep] [uniqueidentifier] NULL,
[kore_ticketingsalesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingsalesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingservicerep] [uniqueidentifier] NULL,
[kore_ticketingservicerepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingservicerepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_type] [int] NULL,
[kore_typename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastusedincampaign] [datetime] NULL,
[leadsourcecode] [int] NULL,
[leadsourcecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[li_companyid] [int] NULL,
[li_membertoken] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managername] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managerphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterid] [uniqueidentifier] NULL,
[merged] [bit] NULL,
[mergedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middlename] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilephone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_40_60paymentamt] [money] NULL,
[new_40_60paymentamt_base] [money] NULL,
[new_5monthlypaymentamt] [money] NULL,
[new_5monthlypaymentamt_base] [money] NULL,
[new_address1_metroarea] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_afyfnetwork] [bit] NULL,
[new_afyfnetworkname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_allocatedseatlocation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ambffnewsletter] [bit] NULL,
[new_ambffnewslettername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ambfftrustees] [bit] NULL,
[new_ambfftrusteesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_americanexplorers] [bit] NULL,
[new_americanexplorersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_atlantafalconsnationalfootballleague] [bit] NULL,
[new_atlantafalconsnationalfootballleaguename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_atlantaunitedfceventsfanperksa] [bit] NULL,
[new_atlantaunitedfceventsfanperksaname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_atlantaunitedfcmajorleaguesoccer] [bit] NULL,
[new_atlantaunitedfcmajorleaguesoccername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_atlutdacct] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_atlutdgrouptickets] [bit] NULL,
[new_atlutdgroupticketsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_atlutdseasontickets] [bit] NULL,
[new_atlutdseasonticketsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_atlutdsinglegametickets] [bit] NULL,
[new_atlutdsinglegameticketsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_brokerflag] [bit] NULL,
[new_brokerflagname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_contactlookup] [uniqueidentifier] NULL,
[new_contactlookupname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_contactlookupyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_currentseasonaccountholder] [bit] NULL,
[new_currentseasonaccountholdername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_currentspend] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_domeaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_domecontractend] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_domecontractescalator] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_domecontractext] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_domecontractstart] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_domeseats] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_excludefrommbsemails] [int] NULL,
[new_excludefrommbsemailsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_falconsnassurveylink] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_fancouncilurl] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_favoriteplayer] [int] NULL,
[new_favoriteplayername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_foundationsubscription] [uniqueidentifier] NULL,
[new_foundationsubscriptionname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_foundationsubscriptionyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_futurephasenotes] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_futurephaserep] [uniqueidentifier] NULL,
[new_futurephaserepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_futurephaserepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_georgiadomeseats] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_haskidsunder18] [bit] NULL,
[new_haskidsunder18name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_importsource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_interestlevel] [int] NULL,
[new_interestlevelname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_interesttype] [int] NULL,
[new_interesttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_memorieslastupdated] [datetime] NULL,
[new_memoriesredeemedcredits] [int] NULL,
[new_memoriesregisteredmember] [bit] NULL,
[new_memoriesregisteredmembername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_memoriesremainingcredits] [int] NULL,
[new_memoriesstartingcredits] [int] NULL,
[new_miscfield] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_mlsfounderssurveylink] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_mlslivecode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_myfinder] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_new_subscription_mlsofficialgearmail] [bit] NULL,
[new_new_subscription_mlsofficialgearmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nflaccount] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nflaccountpassword] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nflmc1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nflmccode1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nflmccode2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nflmccode3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nflmccode4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nflmcurl2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nsappointmentidentifier] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nscheckedoutby] [uniqueidentifier] NULL,
[new_nscheckedoutbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nscheckedoutbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nscheckedoutuntil] [datetime] NULL,
[new_nsclubinterest] [bit] NULL,
[new_nsclubinterestname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nsclubseatinterest] [int] NULL,
[new_nsclubseatinterestname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nslicenseename] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nspasscode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nspurl] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nsrepemail] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nsrepphone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nsreservationdate] [datetime] NULL,
[new_nsreserveinterest] [bit] NULL,
[new_nsreserveinterestname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nsreserveseatinterest] [int] NULL,
[new_nsreserveseatinterestname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nssuiteinterest] [bit] NULL,
[new_nssuiteinterestname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_nswaitlistconfirmed] [bit] NULL,
[new_nswaitlistconfirmedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_numberofseats] [int] NULL,
[new_numberofseatsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_numberoftickets] [int] NULL,
[new_numberofticketsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ordernumberprioirtynumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_personalurl] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_pif_amount] [money] NULL,
[new_pif_amount_base] [money] NULL,
[new_pslacct] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_pslacctmgrpin] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_referralrecordid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_relocationdatetime] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_seatingpreference] [int] NULL,
[new_seatingpreferencename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_sgbgamespurchased] [int] NULL,
[new_sgbmoneyspent] [money] NULL,
[new_sgbmoneyspent_base] [money] NULL,
[new_sgbticketspurchased] [int] NULL,
[new_sharepartner] [bit] NULL,
[new_sharepartnername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_somethingelse] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_source] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_sponsorshipcheckedoutby] [uniqueidentifier] NULL,
[new_sponsorshipcheckedoutbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_sponsorshipcheckedoutbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_sponsorshipcheckedoutuntil] [datetime] NULL,
[new_subscription_ereport] [bit] NULL,
[new_subscription_ereportname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscription_gearmail] [bit] NULL,
[new_subscription_gearmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscription_mlssubscription] [bit] NULL,
[new_subscription_mlssubscriptionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscription_postgame_sth] [bit] NULL,
[new_subscription_postgame_sthname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscription_preferredpartner] [bit] NULL,
[new_subscription_preferredpartnername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscription_pregame_sth] [bit] NULL,
[new_subscription_pregame_sthname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscription_ticket_offers] [bit] NULL,
[new_subscription_ticket_offersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscription_ticketsuitesales] [bit] NULL,
[new_subscription_ticketsuitesalesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_subscriptionnewstadiuminformationoffers] [bit] NULL,
[new_subscriptionnewstadiuminformationoffersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_tegamespurchased] [int] NULL,
[new_temoneyspent] [money] NULL,
[new_temoneyspent_base] [money] NULL,
[new_teticketspurchased] [int] NULL,
[new_topcontact] [int] NULL,
[new_typeofgroup] [int] NULL,
[new_typeofgroupname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_unitedcheckedoutby] [uniqueidentifier] NULL,
[new_unitedcheckedoutbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_unitedcheckedoutbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_unitedcheckedoutuntil] [datetime] NULL,
[new_unitedsurveyreferral] [bit] NULL,
[new_unitedsurveyreferralname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_utdacct] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_utdenrolledinautorenewal] [bit] NULL,
[new_utdenrolledinautorenewalname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_utdfirstorderdate] [datetime] NULL,
[new_utdofseats] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_utdorderpriority] [int] NULL,
[new_utdseatingpreferfence] [int] NULL,
[new_utdseatingpreferfencename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_virtualseatview] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_wnpfnetwork] [bit] NULL,
[new_wnpfnetworkname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nickname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numberofchildren] [int] NULL,
[originatingleadid] [uniqueidentifier] NULL,
[originatingleadidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originatingleadidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owningbusinessunit] [uniqueidentifier] NULL,
[owningteam] [uniqueidentifier] NULL,
[owninguser] [uniqueidentifier] NULL,
[pager] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactid] [uniqueidentifier] NULL,
[parentcontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomerid] [uniqueidentifier] NULL,
[parentcustomeridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridyominame] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[participatesinworkflow] [bit] NULL,
[participatesinworkflowname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymenttermscode] [int] NULL,
[paymenttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmentdaycode] [int] NULL,
[preferredappointmentdaycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmenttimecode] [int] NULL,
[preferredappointmenttimecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredcontactmethodcode] [int] NULL,
[preferredcontactmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredequipmentid] [uniqueidentifier] NULL,
[preferredequipmentidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredserviceid] [uniqueidentifier] NULL,
[preferredserviceidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuserid] [uniqueidentifier] NULL,
[preferredsystemuseridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuseridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[processid] [uniqueidentifier] NULL,
[salutation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingmethodcode] [int] NULL,
[shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sp_convertedon] [datetime] NULL,
[sp_engageid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sp_synctoengage] [bit] NULL,
[sp_synctoengagename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spousesname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stageid] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suffix] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territorycode] [int] NULL,
[territorycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timezoneruleversionnumber] [int] NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[traversedpath] [nvarchar] (1250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[websiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifirstname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifullname] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomilastname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomimiddlename] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CopyLoadDate] [datetime] NOT NULL CONSTRAINT [DF_ProdCopystg_Contact] DEFAULT (getdate()),
[client_2016pslpaymentpaid] [bit] NULL,
[client_2016pslpaymentpaidname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_2017pslamountdue] [money] NULL,
[client_2017pslamountdue_base] [money] NULL,
[client_2017pslpaymentpaid] [bit] NULL,
[client_2017pslpaymentpaidname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_academyteam] [bit] NULL,
[client_academyteamname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_academytriedout] [bit] NULL,
[client_academytriedoutname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ambffsuppression] [bit] NULL,
[client_ambffsuppressionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_associatedarchticsidsuiteowneradmin] [int] NULL,
[client_atlantaunitedstayconnectedsignupdate] [datetime] NULL,
[client_badcontactinfo] [bit] NULL,
[client_badcontactinfoname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_bademailaddresses] [bit] NULL,
[client_bademailaddressesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_badphonenumbers] [bit] NULL,
[client_badphonenumbersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_corporateentertainment] [bit] NULL,
[client_corporateentertainmentname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_executivemembers] [bit] NULL,
[client_executivemembersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_falconsclubowner] [bit] NULL,
[client_falconsclubownername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_falconsemailscore] [float] NULL,
[client_falconsgroup] [bit] NULL,
[client_falconsgroupname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_falconslogeowner] [bit] NULL,
[client_falconslogeownername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_falconsprospect] [bit] NULL,
[client_falconsprospectname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_falconssgbtetf] [bit] NULL,
[client_falconssgbtetfname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_forcetosp] [bit] NULL,
[client_forcetospname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_foundingmember] [bit] NULL,
[client_foundingmembername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_foundingmembersnoseats] [bit] NULL,
[client_foundingmembersnoseatsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_groupsize] [int] NULL,
[client_groupsizename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_grouptype] [int] NULL,
[client_grouptypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lastunitedrep] [uniqueidentifier] NULL,
[client_lastunitedrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lastunitedrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mbsparttimepositioninterest] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mbsseatingpreferences] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mbssuiteowner] [bit] NULL,
[client_mbssuiteownername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mbswebleaddateadded] [datetime] NULL,
[client_mbswinbackscore] [float] NULL,
[client_membercharacteristics1] [int] NULL,
[client_membercharacteristics1name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_membercharacteristics2] [int] NULL,
[client_membercharacteristics2name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_memberreward] [int] NULL,
[client_memberrewardname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_membertype] [int] NULL,
[client_membertypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mobileticketingtestgroup] [bit] NULL,
[client_mobileticketingtestgroupname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_parttimepositioninterest] [int] NULL,
[client_parttimepositioninterestname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_playoffpayment] [bit] NULL,
[client_playoffpaymentname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_preferredprice] [int] NULL,
[client_preferredpricename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_preferredticketprice] [int] NULL,
[client_preferredticketpricename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pslowner] [bit] NULL,
[client_pslownername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_questionorcomment] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_referredby] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_seatinglevelpreference] [int] NULL,
[client_seatinglevelpreferencename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_signatureservicesrep] [uniqueidentifier] NULL,
[client_signatureservicesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_signatureservicesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_sp_optoutambff] [bit] NULL,
[client_sp_optoutambffname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_sp_optoutatlutd] [bit] NULL,
[client_sp_optoutatlutdname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_sp_optoutfalcons] [bit] NULL,
[client_sp_optoutfalconsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_trackingnumber] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_unitedgtupdates] [int] NULL,
[client_unitedgtupdatesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_unsubscribefromcd] [bit] NULL,
[client_unsubscribefromcdname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdacceptedtcnotautorenewal] [bit] NULL,
[client_utdacceptedtcnotautorenewalname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdadditionalcomments] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdgroup] [bit] NULL,
[client_utdgroupname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdgroupsize] [int] NULL,
[client_utdgroupsizename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdgrouptype] [int] NULL,
[client_utdgrouptypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdmultigame] [bit] NULL,
[client_utdmultigamename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdmultipackbuyer] [bit] NULL,
[client_utdmultipackbuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdseasonticketholder] [bit] NULL,
[client_utdseasonticketholdername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdseasontixdue] [money] NULL,
[client_utdseasontixdue_base] [money] NULL,
[client_utdsgbtetf] [bit] NULL,
[client_utdsgbtetfname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdsinglematchbuyer] [bit] NULL,
[client_utdsinglematchbuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_utdwebleaddateadded] [datetime] NULL,
[client_falconsservicerep] [uniqueidentifier] NULL,
[client_falconsservicerepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_falconsservicerepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_internalaccount] [bit] NULL,
[client_internalaccountname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mbstourcheckedoutby] [uniqueidentifier] NULL,
[client_mbstourcheckedoutbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mbstourcheckedoutbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_unitedstm2018] [bit] NULL,
[client_unitedstm2018name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [ProdcopyStg].[Contact_old] ADD CONSTRAINT [Prodcopystg_Contact_old_PK] PRIMARY KEY CLUSTERED  ([contactid])
GO
